import type { Metadata } from "next";
import { Fuzzy_Bubbles } from "next/font/google";
import "./globals.css";

const FuzzyBubbles = Fuzzy_Bubbles({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={FuzzyBubbles.variable}>
      <body>{children}</body>
    </html>
  );
}
